on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single job
      uses: appleboy/jenkins-action@master
      with:
       url: "https://jenkins.sdpmlab.org"
       user: "Sampling8291"
       token: ${{secrets.TOKEN}}
       job: "tcse2023-5idereal"
    
